### ISSUE TITLE
what version of mcreator to use?

### ISSUE THREAD

**Issue by c0d3rb0y** [Goldorion/MCreatorSpigotGenerator#18]
i am using 2020.3 mcreator and it won't load. help

**Comment by CrispyChips6660** [comment]
"To use the latest version of the plugin, you need to have the latest version of MCreator, **including snapshots.**"
I mean can't you read the full description of this plugin...

**Comment by c0d3rb0y** [comment]
can someone give a link to the snapshot mcreator then because i can't find it's download

**Comment by c0d3rb0y** [comment]
or a way to get it

**Comment by CrispyChips6660** [comment]
https://mcreator.net/download

![lmao](https://i.ibb.co/Vjs6jVj/Screen-Shot-2020-08-01-at-12-07-45-PM.png)

**Comment by c0d3rb0y** [comment]
oh i'm just really blind then, scrolled right past

**Comment by Goldorion** [comment]
It doesn't work and it will never work because MCreator 2020.3 doesn't support the Spigot workspace type.
