### ISSUE TITLE
Plugin does not work on 2020.4

### ISSUE THREAD

**Issue by newuser929399** [Goldorion/MCreatorSpigotGenerator#22]
As the title states, the plugin for me is not working on the latest release (2020.4), nor the snapshots

**Comment by Goldorion** [comment]
Can you give details, say what specifically, what is your version, give the console if you have an error, your mcreator.log, etc?

**Comment by newuser929399** [comment]
Executing 
    Gradle task: dependencies buildLatestSpigot --refresh-dependencies

Build 
    info: MCreator 2020.4.32115, spigot-1.16.2, 64-bit, 16267 MB, Windows 10, 
    JVM 1.8.0_252, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk

org.gradle.tooling.GradleConnectionException: 
    Could not install Gradle distribution from 
    'https://services.gradle.org/distributions/gradle-6.1.1-bin.zip'.


 
      at 
    org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(
DistributionFactory.java:139
)

 
      at 
    org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(
CachingToolingImplementationLoader.java:41
)

 
      at 
    org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(
SynchronizedToolingImplementationLoader.java:44
)

 
      at 
    org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(
LazyConsumerActionExecutor.java:147
)

 
      at 
    org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(
LazyConsumerActionExecutor.java:129
)

 
      at 
    org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(
CancellableConsumerActionExecutor.java:45
)

 
      at 
    org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(
ProgressLoggingConsumerActionExecutor.java:61
)

 
      at 
    org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(
RethrowingErrorsConsumerActionExecutor.java:38
)

 
      at 
    org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.lambda$run$0(
DefaultAsyncConsumerActionExecutor.java:62
)

 
      at 
    org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(
ExecutorPolicy.java:64
)

 
      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(
ManagedExecutorImpl.java:48
)

 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(
ThreadPoolExecutor.java:1149
)

 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(
ThreadPoolExecutor.java:624
)

 
      at 
    org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(
ThreadFactoryImpl.java:56
)

 
      at java.lang.Thread.run(
Thread.java:748
)

Caused 
    by: java.lang.RuntimeException: Timeout of 120000 reached waiting for 
    exclusive access to file: 
    C:\Users\legen.000\.mcreator\gradle\wrapper\dists\gradle-6.1.1-bin\4i3ntwqiazourd86epxcz427c\gradle-6.1.1-bin.zip


 
      at org.gradle.wrapper.ExclusiveFileAccessManager.access(
ExclusiveFileAccessManager.java:65
)

 
      at org.gradle.wrapper.Install.createDist(
Install.java:48
)

 
      at org.gradle.tooling.internal.consumer.DistributionInstaller.install(
DistributionInstaller.java:72
)

 
      at 
    org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(
DistributionFactory.java:133
)

 
      ... 14 more


TASK 
    EXECUTION FAILED

Task 
    completed in 120337 milliseconds

**Comment by BoogieMonster1O1** [comment]
Do you have a good internet connection? You might want to check on that

**Comment by newuser929399** [comment]
Oh, mb, turns out i had to reinstall my network drivers f

**Comment by newuser929399** [comment]
Also, sorry for being a bother, but the only thing I could get to work is the command, procedures don't do anything. I tried sending a message in chat, giving XP to the player, etc, however, it won't work

**Comment by Goldorion** [comment]
I will improve everything with the time, but you should be able some procedure blocks.
