### ISSUE TITLE
Procedure blocks using PlayerEntity don't work

### ISSUE THREAD

**Issue by U1timateJ7** [Goldorion/MCreatorSpigotGenerator#23]
Console:
Executing 
    Gradle task: build

Build 
    info: MCreator 2020.4.32115, spigot-1.16.2, 64-bit, 6028 MB, Windows 10, 
    JVM 1.8.0_252, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk

> 
    Task :compileJava FAILED

C:\Users\ultim\MCreatorWorkspaces\ulto_plugin\src\main\java\com\ulto\plugin\procedures\WorkbenchProcedure.java:7: 
    error: cannot find symbol 
 
         player.openWorkbench(player.getLocation(), true);

 
                              ^

 
     symbol:   variable player

 
     location: class WorkbenchProcedure

C:\Users\ultim\MCreatorWorkspaces\ulto_plugin\src\main\java\com\ulto\plugin\procedures\WorkbenchProcedure.java:7: 
    error: cannot find symbol 
 
         player.openWorkbench(player.getLocation(), true);

 
         ^

 
     symbol:   variable player

 
     location: class WorkbenchProcedure

2 
    errors

FAILURE: 
    Build failed with an exception.

* 
    What went wrong:

Execution 
    failed for task ':compileJava'.

> 
    Compilation failed; see the compiler error output for details.

* 
    Try:

Run 
    with --stacktrace option to get the stack trace. Run with --info or 
    --debug option to get more log output. Run with --scan to get full 
    insights.

* 
    Get more help at https://help.gradle.org

BUILD 
    FAILED in 391ms

1 
    actionable task: 1 executed

BUILD 
    FAILED

Task 
    completed in 3074 milliseconds

[an example workspace](https://github.com/ClothCreators/MCreatorSpigotGenerator/files/5086485/example.zip)

**Comment by Goldorion** [comment]
Can you give me a test workspace please?

**Comment by U1timateJ7** [comment]
sure
[example.zip](https://github.com/ClothCreators/MCreatorSpigotGenerator/files/5106827/example.zip)

**Comment by Goldorion** [comment]
Thank you, I will check as soon as possible.

**Comment by Goldorion** [comment]
I found the cause and I will fix it as soon as I have some time. I removed something, I used in some entity procedure blocks, that was generated when an entity dependy was used, but I forgot to update procedure blocks.

**Comment by AnnikenYT** [comment]
Has this been fixed yet?
