### ISSUE TITLE
Hello if i want to Run server and Client it will give me that error.

### ISSUE THREAD

**Issue by tevuori** [Goldorion/MCreatorSpigotGenerator#24]
Executing Gradle task: runSpigotServer 
Build info: MCreator 2020.4.32115, spigot-1.16.2, 64-bit, 16342 MB, Windows 10, JVM 1.8.0_252, JAVA_HOME: D:\Program Files\Pylo\MCreator\jdk 
> Task :compileJava UP-TO-DATE 
> Task :processResources UP-TO-DATE 
> Task :classes UP-TO-DATE 
> Task :jar UP-TO-DATE 
> Task :assemble UP-TO-DATE 
> Task :compileTestJava NO-SOURCE 
> Task :processTestResources NO-SOURCE 
> Task :testClasses UP-TO-DATE 
> Task :test NO-SOURCE 
> Task :check UP-TO-DATE 
> Task :build UP-TO-DATE 
> Task :runSpigotServer FAILED 
Error: Unable to access jarfile spigot-1.16.1.jar 
FAILURE: Build failed with an exception. 
* Where: 
Build file 'C:\Users\kubah\MCreatorWorkspaces\hello_world\build.gradle' line: 47 
* What went wrong: 
Execution failed for task ':runSpigotServer'. 
> Process 'command 'D:\Program Files\Pylo\MCreator\jdk\bin\java.exe'' finished with non-zero exit value 1 
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 375ms 
4 actionable tasks: 1 executed, 3 up-to-date 
BUILD FAILED 
Task completed in 437 milliseconds

**Comment by Goldorion** [comment]
Can you give me more info, please? I tried and I don't have an error.

**Comment by hsnbozkurt** [comment]
Same error here
