### ISSUE TITLE
Can't even create plugins using this generator

### ISSUE THREAD

**Issue by ghost** [Goldorion/MCreatorSpigotGenerator#26]
Whenever I try to create a plugin, it gives me this error:

**Java JVM used by Gradle ran out of available RAM!**
The amount of RAM allocated to Java JVM used by Gradle is too low.
You can change this setting in MCreator's preferences under Gradle options section.

It does not give me this error for ANYTHING else I try to create. Just plugins I create using this generator. It also always stops at this:

Final mapped jar: work\mapped.(random numbers and letters).jar does not exist, creating (please wait)!
Picked up _JAVA_OPTIONS: -Djdk.net.URLClassPath.disableClassPathURLCheck=true

also here's an error log
[error.txt](https://github.com/ClothCreators/MCreatorSpigotGenerator/files/5233515/error.txt)

**Comment by BoogieMonster1O1** [comment]
explain

**Comment by BoogieMonster1O1** [comment]
I've pushed a commit that might fix this to my branch. Please let me know if it doesn't work. 
[Link](https://github.com/ClothCreators/MCreatorSpigotGenerator/files/5233525/Archive.zip)

**Comment by ghost** [comment]
still doesn't work for me
