### ISSUE TITLE
Can't use Spigot plugin.

### ISSUE THREAD

**Issue by KikoCraft** [Goldorion/MCreatorSpigotGenerator#30]
**I tried creating a Spigot plugin. It says it can't create new workspace. "Build failed".

I checked my MCReator version and updated Java. Still not working.

Anyone know why is that?**

 

I copied error to clipboard, here it is.

Executing
    Gradle task: dependencies buildLatestSpigot --refresh-dependencies

Build
    info: MCreator 2020.5.47520, spigot-1.16.4, 64-bit, 8026 MB, Windows 10,
    JVM 1.8.0_265, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk

>
    Task :dependencies

------------------------------------------------------------

Root
    project

------------------------------------------------------------

annotationProcessor
    - Annotation processors and their dependencies for source set 'main'.

No
    dependencies

apiElements
    - API elements for main. (n)

No
    dependencies

archives
    - Configuration for archive artifacts.

No
    dependencies

compileClasspath
    - Compile classpath for source set 'main'.

\---
    org.spigotmc:spigot-api:1.16.4-R0.1-SNAPSHOT

 
        +--- commons-lang:commons-lang:2.6

 
        +--- com.google.guava:guava:21.0

 
        +--- com.google.code.gson:gson:2.8.0

 
        +--- net.md-5:bungeecord-chat:1.16-R0.3

 
        |    +--- com.google.code.gson:gson:2.8.0

 
        |    \--- com.google.guava:guava:21.0

 
        \--- org.yaml:snakeyaml:1.26

compileOnly
    - Compile only dependencies for source set 'main'. (n)

\---
    org.spigotmc:spigot-api:1.16.4-R0.1-SNAPSHOT (n)

default
    - Configuration for default artifacts.

No
    dependencies

implementation
    - Implementation only dependencies for source set 'main'. (n)

No
    dependencies

runtimeClasspath
    - Runtime classpath of source set 'main'.

No
    dependencies

runtimeElements
    - Elements of runtime for main. (n)

No
    dependencies

runtimeOnly
    - Runtime only dependencies for source set 'main'. (n)

No
    dependencies

testAnnotationProcessor
    - Annotation processors and their dependencies for source set 'test'.

No
    dependencies

testCompileClasspath
    - Compile classpath for source set 'test'.

No
    dependencies

testCompileOnly
    - Compile only dependencies for source set 'test'. (n)

No
    dependencies

testImplementation
    - Implementation only dependencies for source set 'test'. (n)

No
    dependencies

testRuntimeClasspath
    - Runtime classpath of source set 'test'.

No
    dependencies

testRuntimeOnly
    - Runtime only dependencies for source set 'test'. (n)

No
    dependencies

(o)
    - dependencies omitted (listed previously)

(n)
    - Not resolved (configuration is not meant to be resolved)

A
    web-based, searchable dependency report is available by adding the --scan
    option.

>
    Task :buildLatestSpigot

Download
    https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/art…

Loading
    BuildTools version: git-BuildTools-7fe9375-122 (#122)

Java
    Version: Java 8

Current
    Path: C:\Users\Korisnik\MCreatorWorkspaces\resawsd\build\btmp\.

    Could not find PortableGit installation, downloading. 

Starting
    download of
    https://static.spigotmc.org/git/PortableGit-2.24.1.2-64-bit.7z.exe

Downloaded
    file: PortableGit-2.24.1.2-64-bit\PortableGit-2.24.1.2-64-bit.7z.exe with
    hash: cb75e4a557e01dd27b5af5eb59dfe28adcbad21638777dd686429dd905d13899

Extracting
    downloaded git install

Exception
    in thread "main" java.lang.RuntimeException: Error running command, return
    status !=0: [cmd.exe, /D, /C,
    C:\Users\Korisnik\MCreatorWorkspaces\resawsd\build\btmp\PortableGit-2.24.1.2-64-bit\PortableGit-2.24.1.2-64-bit.7z.exe,
    -y, -gm2, -nr]

 
      at org.spigotmc.builder.Builder.runProcess0(
Builder.java:819
 
      at org.spigotmc.builder.Builder.runProcess0(Builder.java:819)

 
      at org.spigotmc.builder.Builder.runProcess(
Builder.java:756
 
      at org.spigotmc.builder.Builder.runProcess(Builder.java:756)

 
      at org.spigotmc.builder.Builder.main(
Builder.java:211
 
      at org.spigotmc.builder.Builder.main(Builder.java:211)

 
      at org.spigotmc.builder.Bootstrap.main(
Bootstrap.java:34
 
      at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:34)

>
    Task :buildLatestSpigot FAILED

FAILURE:
    Build failed with an exception.

-
    Where:

Build
    file 'C:\Users\ME\MCreatorWorkspaces\resawsd\build.gradle' line: 28

-
    What went wrong:

Execution
    failed for task ':buildLatestSpigot'.

>
    Process 'command 'C:\Program Files\Pylo\MCreator\jdk\bin\java.exe''
    finished with non-zero exit value 1

-
    Try:

Run
    with --stacktrace option to get the stack trace. Run with --info or
    --debug option to get more log output. Run with --scan to get full
    insights.

-
    Get more help at https://help.gradle.org

BUILD
    FAILED in 1m 31s

2
    actionable tasks: 2 executed

BUILD
    FAILED

Task
    completed in 92266 milliseconds

 

 

 

For some reason it says it stops gradle.

Setting up Gradle project files > Stopping running Gradle > Setting up Gradle project > and then it don't do anything

**Comment by belovarseny** [comment]
You have been hacked by cheater777
