### ISSUE TITLE
1.15.2 support please

### ISSUE THREAD

**Issue by Wolfyxon** [Goldorion/MCreatorSpigotGenerator#31]
i want 1.15.2 support. why there is only 1.16.1 - 1.16.4 ?

**Comment by Goldorion** [comment]
> why there is only 1.16.1 - 1.16.4 ?

Maybe because I updated the plugin to Minecraft 1.16.4.

**Comment by Wolfyxon** [comment]
But i have some servers with older versions and I want to make plugins for them
