### ISSUE TITLE
Get variable from Command

### ISSUE THREAD

**Issue by iambenmitchell** [Goldorion/MCreatorSpigotGenerator#33]
Hi, I want to do something like

/command var1 var2

and then have it write to a json file like so:

```
{
  "name": "var1",
  "name2": "var2"
}
```

Also, a nice feature would be to have the procedure run every x seconds

**Comment by Goldorion** [comment]
This feature has been implemented in File Manager. https://mcreator.net/plugin/64638/file-creator
