### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by Faris90** [Goldorion/MCreatorSpigotGenerator#36]
Executing 
    Gradle task: dependencies buildLatestSpigot --refresh-dependencies

Build 
    info: MCreator 2020.5.47520, spigot-1.16.4, 64-bit, 16225 MB, Windows 10, 
    JVM 1.8.0_265, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk

> 
    Task :dependencies

------------------------------------------------------------

Root 
    project

------------------------------------------------------------

annotationProcessor 
    - Annotation processors and their dependencies for source set 'main'.

No 
    dependencies

apiElements 
    - API elements for main. (n)

No 
    dependencies

archives 
    - Configuration for archive artifacts.

No 
    dependencies

compileClasspath 
    - Compile classpath for source set 'main'.

\--- 
    org.spigotmc:spigot-api:1.16.4-R0.1-SNAPSHOT

 
        +--- commons-lang:commons-lang:2.6

 
        +--- com.google.guava:guava:21.0

 
        +--- com.google.code.gson:gson:2.8.0

 
        +--- net.md-5:bungeecord-chat:1.16-R0.3

 
        |    +--- com.google.code.gson:gson:2.8.0

 
        |    \--- com.google.guava:guava:21.0

 
        \--- org.yaml:snakeyaml:1.26

compileOnly 
    - Compile only dependencies for source set 'main'. (n)

\--- 
    org.spigotmc:spigot-api:1.16.4-R0.1-SNAPSHOT (n)

default 
    - Configuration for default artifacts.

No 
    dependencies

implementation 
    - Implementation only dependencies for source set 'main'. (n)

No 
    dependencies

runtimeClasspath 
    - Runtime classpath of source set 'main'.

No 
    dependencies

runtimeElements 
    - Elements of runtime for main. (n)

No 
    dependencies

runtimeOnly 
    - Runtime only dependencies for source set 'main'. (n)

No 
    dependencies

testAnnotationProcessor 
    - Annotation processors and their dependencies for source set 'test'.

No 
    dependencies

testCompileClasspath 
    - Compile classpath for source set 'test'.

No 
    dependencies

testCompileOnly 
    - Compile only dependencies for source set 'test'. (n)

No 
    dependencies

testImplementation 
    - Implementation only dependencies for source set 'test'. (n)

No 
    dependencies

testRuntimeClasspath 
    - Runtime classpath of source set 'test'.

No 
    dependencies

testRuntimeOnly 
    - Runtime only dependencies for source set 'test'. (n)

No 
    dependencies

(*) 
    - dependencies omitted (listed previously)

(n) 
    - Not resolved (configuration is not meant to be resolved)

A 
    web-based, searchable dependency report is available by adding the --scan 
    option.

> 
    Task :buildLatestSpigot

Download 
    https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

Loading 
    BuildTools version: git-BuildTools-36c11e9-126 (#126)

Java 
    Version: Java 8

Current 
    Path: C:\Users\hp\MCreatorWorkspaces\spoggy\build\btmp\.

*** 
    Using downloaded git PortableGit-2.30.0-64-bit\PortableGit ***

*** 
    Please note that this is a beta feature, so if it does not work please 
    also try a manual install of git from https://git-for-windows.github.io/ 
    ***

git 
    version 2.30.0.windows.1

BuildTools

unconfigured@null.spigotmc.org

Attempting 
    to build version: '1.16.4' use --rev <version> to override

Found 
    version

{

 
      "name": "2987",

 
      "description": "Jenkins build 2987",

 
      "refs": {

 
         "BuildData": "501ea060743c7bba4436878207e4f1232298efce",

 
         "Bukkit": "0958895aefcccb79abb4d703d5a8694af7416e4a",

 
         "CraftBukkit": "7a6c3c9aa6e48de164aeeb78052a7775f3f81c30",

 
         "Spigot": "a93cbb1e986c59ffd888f072490db0afe4119093"

 
      },

 
      "toolsVersion": 105,

 
      "javaVersions": [52, 59]

}

Pulling 
    updates for C:\Users\hp\MCreatorWorkspaces\spoggy\build\btmp\BuildData\.git

Successfully 
    fetched updates!

Checked 
    out: 501ea060743c7bba4436878207e4f1232298efce

Pulling 
    updates for C:\Users\hp\MCreatorWorkspaces\spoggy\build\btmp\Bukkit\.git

Successfully 
    fetched updates!

Checked 
    out: 0958895aefcccb79abb4d703d5a8694af7416e4a

Pulling 
    updates for 
    C:\Users\hp\MCreatorWorkspaces\spoggy\build\btmp\CraftBukkit\.git

Successfully 
    fetched updates!

Checked 
    out: 7a6c3c9aa6e48de164aeeb78052a7775f3f81c30

Pulling 
    updates for C:\Users\hp\MCreatorWorkspaces\spoggy\build\btmp\Spigot\.git

Successfully 
    fetched updates!

Checked 
    out: a93cbb1e986c59ffd888f072490db0afe4119093

Attempting 
    to build Minecraft with details: VersionInfo(minecraftVersion=1.16.4, 
    accessTransforms=bukkit-1.16.4.at, classMappings=bukkit-1.16.4-cl.csrg, 
    memberMappings=bukkit-1.16.4-members.csrg, packageMappings=package.srg, 
    minecraftHash=c43dc4c1bda4f485428fc60d5b998270, classMapCommand=java -jar 
    BuildData/bin/SpecialSource-2.jar map --only . --only net/minecraft 
    --auto-lvt BASIC --auto-member SYNTHETIC -e 
    BuildData/mappings/bukkit-1.16.4.exclude -i {0} -m {1} -o {2}, 
    memberMapCommand=java -jar BuildData/bin/SpecialSource-2.jar map --only . 
    --only net/minecraft --auto-member LOGGER --auto-member TOKENS -i {0} -m 
    {1} -o {2}, finalMapCommand=java -jar BuildData/bin/SpecialSource.jar 
    --only . --only net/minecraft -i {0} --access-transformer {1} -m {2} -o 
    {3}, decompileCommand=java -jar BuildData/bin/fernflower.jar -dgs=1 -hdc=0 
    -asc=1 -udv=0 -rsy=1 -aoa=1 {0} {1}, 
    serverUrl=https://launcher.mojang.com/v1/objects/35139deedbd5182953cf1caa23835da59ca3d7cd/server.jar, 
    toolsVersion=105)

Found 
    good Minecraft hash (c43dc4c1bda4f485428fc60d5b998270)

Final 
    mapped jar: work\mapped.13da6e65.jar does not exist, creating (please 
    wait)!

Picked 
    up _JAVA_OPTIONS: -Djdk.net.URLClassPath.disableClassPathURLCheck=true

Exception 
    in thread "main" java.lang.OutOfMemoryError: Java heap space

 
      at org.objectweb.asm.tree.MethodNode.visitFrame(
MethodNode.java:332
 
      at org.objectweb.asm.tree.MethodNode.visitFrame(MethodNode.java:332)

 
      at org.objectweb.asm.ClassReader.readCode(
ClassReader.java:2046
 
      at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2046)

 
      at org.objectweb.asm.ClassReader.readMethod(
ClassReader.java:1488
 
      at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1488)

 
      at org.objectweb.asm.ClassReader.accept(
ClassReader.java:718
 
      at org.objectweb.asm.ClassReader.accept(ClassReader.java:718)

 
      at org.objectweb.asm.ClassReader.accept(
ClassReader.java:401
 
      at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)

 
      at net.md_5.ss.repo.JarRepo.getClass0(
JarRepo.java:38
 
      at net.md_5.ss.repo.JarRepo.getClass0(JarRepo.java:38)

 
      at net.md_5.ss.repo.ClassRepo.getClass(
ClassRepo.java:22
 
      at net.md_5.ss.repo.ClassRepo.getClass(ClassRepo.java:22)

 
      at net.md_5.ss.repo.JarRepo$1.computeNext(
JarRepo.java:69
 
      at net.md_5.ss.repo.JarRepo$1.computeNext(JarRepo.java:69)

 
      at net.md_5.ss.repo.JarRepo$1.computeNext(
JarRepo.java:53
 
      at net.md_5.ss.repo.JarRepo$1.computeNext(JarRepo.java:53)

 
      at com.google.common.collect.AbstractIterator.tryToComputeNext(
AbstractIterator.java:145
 
      at 
    com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)

 
      at com.google.common.collect.AbstractIterator.hasNext(
AbstractIterator.java:140
 
      at 
    com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)

 
      at com.google.common.collect.MultitransformedIterator.hasNext(
MultitransformedIterator.java:47
 
      at 
    com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:47)

 
      at net.md_5.ss.SpecialSource.map(
SpecialSource.java:123
 
      at net.md_5.ss.SpecialSource.map(SpecialSource.java:123)

 
      at net.md_5.ss.SpecialSource.main(
SpecialSource.java:49
 
      at net.md_5.ss.SpecialSource.main(SpecialSource.java:49)

Exception 
    in thread "main" java.lang.RuntimeException: Error running command, return 
    status !=0: [cmd.exe, /D, /C, java, -jar, 
    BuildData/bin/SpecialSource-2.jar, map, --only, ., --only, net/minecraft, 
    --auto-lvt, BASIC, --auto-member, SYNTHETIC, -e, 
    BuildData/mappings/bukkit-1.16.4.exclude, -i, 
    work\minecraft_server.1.16.4.jar, -m, 
    BuildData/mappings/bukkit-1.16.4-cl.csrg, -o, work\mapped.13da6e65.jar-cl]

 
      at org.spigotmc.builder.Builder.runProcess0(
Builder.java:835
 
      at org.spigotmc.builder.Builder.runProcess0(Builder.java:835)

 
      at org.spigotmc.builder.Builder.runProcess(
Builder.java:772
 
      at org.spigotmc.builder.Builder.runProcess(Builder.java:772)

 
      at org.spigotmc.builder.Builder.main(
Builder.java:439
 
      at org.spigotmc.builder.Builder.main(Builder.java:439)

 
      at org.spigotmc.builder.Bootstrap.main(
Bootstrap.java:27
 
      at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:27)

> 
    Task :buildLatestSpigot FAILED

FAILURE: 
    Build failed with an exception.

* 
    Where:

Build 
    file 'C:\Users\hp\MCreatorWorkspaces\spoggy\build.gradle' line: 28

* 
    What went wrong:

Execution 
    failed for task ':buildLatestSpigot'.

> 
    Process 'command 'C:\Program Files\Pylo\MCreator\jdk\bin\java.exe'' 
    finished with non-zero exit value 1

* 
    Try:

Run 
    with --stacktrace option to get the stack trace. Run with --info or 
    --debug option to get more log output. Run with --scan to get full 
    insights.

* 
    Get more help at https://help.gradle.org

BUILD 
    FAILED in 3m 1s

2 
    actionable tasks: 2 executed

BUILD 
    FAILED

Task 
    completed in 184680 milliseconds

**Comment by Goldorion** [comment]
Use the 1.16.5 version of the plugin.
