### ISSUE TITLE
Cannot Find Symbol (b12313)

### ISSUE THREAD

**Issue by jadenquinn** [Goldorion/MCreatorSpigotGenerator#37]
https://mcreator.net/forum/72468/spigot-1165-cannot-find-symbol - More details.

This is the error. All I did was create a command, and a procedure branching off of said command:
https://pastebin.com/q3Lj9ZK8

Thanks!

**Comment by Goldorion** [comment]
I tried to create a command executing a procedure, and it worked perfectly. Are you sure you have the latest version of the plugin?

**Comment by jadenquinn** [comment]
> I tried to create a command executing a procedure, and it worked perfectly. Are you sure you have the latest version of the plugin?

By the time you commented I don't think I did but at the time I created this issue, yes, I had the latest version of your plugin.
