### ISSUE TITLE
plugin won't work

### ISSUE THREAD

**Issue by VoidNull-0** [Goldorion/MCreatorSpigotGenerator#38]
I tried to run the latest version of the plugin with the latest snapshot and all I got was text that I cant read :/
<img width="1291" alt="thisHappened" src="https://user-images.githubusercontent.com/81176903/114285750-70f11700-9a0e-11eb-86e7-4b4fb8c4d120.png">

**Comment by Goldorion** [comment]
I tested and everything worked fine for me. Try to re-run the setup if you have it again. It often fixes the problem.
