### ISSUE TITLE
Anything with blocks not supported

### ISSUE THREAD

**Issue by 2duviz2** [Goldorion/MCreatorSpigotGenerator#61]
I have a problem making a spigot plugin that if you place a cobweb, after 3 minutes, the block dissapear, but when I try to make it work, anything related to blocks are supported
![image](https://github.com/Goldorion/Spigot-Generator-MCreator/assets/91156184/021b938c-a175-446d-992d-a16191e953e3)

**Comment by 2duviz2** [comment]
> I'm not familiar with the environment so can you elaborate the error a bit further if you can? Thanks.

Well I can't create a procedure that only if you place a cobweb it dissapear after 3600 ticks

**Comment by Goldorion** [comment]
The blocks are not supported for the moment. That's not a bug 🤷
