### ISSUE TITLE
No command?

### ISSUE THREAD

**Issue by skiller8641** [Goldorion/MCreatorSpigotGenerator#62]
i can't add command argument, it says unsupported by generator, its dumb because command are the only human to procedure interaction in plugin
![image](https://github.com/Goldorion/Spigot-Generator-MCreator/assets/94241636/a000b73d-0178-44ef-98ea-c5ce1a689996)
![image](https://github.com/Goldorion/Spigot-Generator-MCreator/assets/94241636/47a66b3f-602a-4a48-8a5f-66288c6bdb35)

**Comment by Goldorion** [comment]
Say this to Spigot 🤷
