### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by durozzzz** [Goldorion/MCreatorSpigotGenerator#66]
![image](https://github.com/Goldorion/Spigot-Generator-MCreator/assets/167654627/437b9676-6823-4f4e-8570-2cdcc84fee9a)
this

**Comment by durozzzz** [comment]
help pls

**Comment by durozzzz** [comment]
bro

**Comment by durozzzz** [comment]
pls someone

**Comment by Goldorion** [comment]
The plugin is not updated as marked on the plugin page.
